### PR TITLE
IKCG-9: about section with images and text (mobile first)

### PR DESCRIPTION
**Pull request by sudijuma**
JIRA-IKCG-9 : https://industrygroup.atlassian.net/browse/IKCG-9

### CODE REVIEW

**Review by EmilBacklund — CHANGES_REQUESTED** [review]
Looks good but do you think you can move the image to the img folder located inside the public folder in root? :D 
And also delete the upload folder.
Maybe you have to fetch from main first to see the folder I'm talking about

**Review by frk-sandkake — CHANGES_REQUESTED** [review]
The code you wrote looks good, so just do as Emil said: pull the last merge from main to secure you have latest version of main in your local repo. Update your branch with these changes and make a new commit/push to your branch, and we can merge it good 😁

**Comment by heshamelmasry77** [comment]
here are the changes you had before

```
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <link rel="icon" type="image/svg+xml" href="" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:ital,wght@0,300;0,400;0,500;0,600;0,700;0,800;1,300;1,400;1,500;1,600;1,700;1,800&display=swap" rel="stylesheet">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Vite App</title>
    <script type="module" src="js/main.js" defer></script>
  </head>
  <body class="bg-slate-400">
<<<<<<< HEAD
    <header class="w-11/12 max-w-[1111px] mx-auto mb-16 mt-8 flex justify-between items-end">
      <div class="logo">
        <img class="w-12 h-12 md:w-16 md:h-16" src="/img/logo.png" alt="logo">
      </div>
      <div class="bg-standardBlack w-44 h-11 md:w-56 md:h-14 hover:bg-galacticBlue rounded-full flex justify-center items-center">
        <p class="text-[14px] md:text-[16px] font-bold text-white">Free Consultation</p>
=======
    <section
      class="w-11/12 max-w-[1111px] mx-auto flex flex-col items-center sm:flex-row space-y-5 md:space-x-5"
    >
      <div class="sm:w-full">
        <img src="./upload/about-me.png" alt="" />
      </div>

      <div
        class="sm:w-full leading-tight text-center sm:text-left p-4 space-y-5"
      >
        <h1 class="text-standardBlack text-smallHeader md:text-smallHeader">
          I’m Amy, and I’d love to work on your next project
        </h1>
        <p class="text-mediumBrown leading-6">
          I love working with others to create beautiful design solutions. I’ve
          designed everything from brand illustrations to complete mobile apps.
          I’m also handy with a camera!
        </p>

        <button
          class="bg-lightRed text-lightCream hover:bg-summerYellow mt-4 px-7 py-4 md:px-11 md:py-6 rounded-full font-bold"
        >
          Free Consultation
        </button>
>>>>>>> 085c5dd (this adds spacing and  alignment)
      </div>
    </header>
    <!--consultation btn-->
    <h1 class="text-center font-bold text-6xl">Design solutions made easy</h1>
    <p class="text-center leading-tight">With over ten years of experience in various design disciplines, I’m your one-stop shop for your design needs.</p>
    <!--Grid section-->
    <div class="w-11/12 max-w-[1111px] mx-auto flex flex-col text-center lg:text-start lg:flex-row justify-between py-14 px-6 md:py-16 md:px-14 lg:py-20 lg:px-16 bg-standardBlack gap-6 text-white rounded-lg items-center">
      <div class="lg:w-8/12 flex flex-col gap-6">
        <h1 class="text-smallHeader md:text-mediumHeader lg:text-largeHeader">Book a call with me</h1>
        <p class="text-body">I’d love to have a chat to see how I can help you. The best first step is for us to discuss your project during a free consultation. Then we can move forward from there.</p>
      </div>
      <div class="flex place-content-end">
        <button class="bg-lightRed hover:bg-summerYellow px-7 py-4 md:px-11 md:py-6 rounded-full font-bold">Free Consultation</button>
      </div>
    </div>
    <footer class="w-11/12 max-w-[1111px] mx-auto mb-14 mt-14 lg:mb-16 flex justify-between items-center">
      <div class="logo">
        <img class="w-12 h-12 md:w-16 md:h-16" src="/img/logo.png" alt="logo">
      </div>
      <div class="bg-standardBlack w-44 h-11 md:w-56 md:h-14 hover:bg-galacticBlue rounded-full flex justify-center items-center">
        <p class="text-[14px] md:text-[16px] font-bold text-white">Free Consultation</p>
      </div>
    </footer>
  </body>
</html>
```

**Comment by heshamelmasry77** [comment]
Go over the changes and see what you want to include in a complete new branch

**Pull request closed without merging**
